FROM oven/bun AS build
WORKDIR /usr/src/app
COPY package.json package.json
COPY bun.lock bun.lock
RUN bun install
COPY ./src ./src
ENV NODE_ENV=production
RUN bun build \
    --compile \
    --minify-whitespace \
    --minify-syntax \
    --outfile server \
    src/index.ts

FROM gcr.io/distroless/base
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/server server
ENV NODE_ENV=production
CMD ["./server"]
EXPOSE 3000
